# PersonalClaw — Homebrew formula.
#
# TWO THINGS HERE ARE UNUSUAL AND BOTH ARE FORCED BY THE SAME MEASUREMENT.
#
# 1. WHY DEPENDENCIES RESOLVE AT INSTALL TIME instead of a vendored `resource` stanza per
#    dependency (the usual Homebrew idiom for a Python CLI, generated by
#    `brew update-python-resources`). `virtualenv_install_with_resources` installs every
#    resource FROM SOURCE (`--no-binary :all:`), and this closure cannot be built from
#    source: `pdfplumber` pulls `pypdfium2`, whose "source" build is a PREBUILT PDFIUM —
#    a Chromium component with no Homebrew formula to link against. Pillow ships 17 bundled
#    codec dylibs, and nh3, cryptography and tree-sitter-language-pack are Rust/C extensions.
#    So it would be ~70 hand-maintained stanzas AND still not work.
#
#    The pinned, checksummed artifact is therefore PersonalClaw's own sdist, with its
#    declared bounds — which upper-bound every specifier that has a known-breaking next
#    major (see the comments in upstream `pyproject.toml`) — resolved by pip with
#    `--prefer-binary`.
#
#    The trade-off, stated plainly: this install is NOT hermetic. It needs network during
#    `brew install`, and two installs on different days can resolve different dependency
#    patch versions. That is exactly the guarantee `pip install personalclaw` gives, which
#    is a first-class supported path in upstream's install matrix — this formula wraps it in
#    a managed venv, a versioned keg and `brew upgrade`, and claims no more than that.
#
# 2. WHY THE VENV IS BUILT IN `post_install` AND NOT IN `install`. Those prebuilt wheels are
#    the reason. After `install`, Homebrew rewrites the Mach-O dylib ID of every MH_DYLIB in
#    the keg to an absolute path under `$(brew --prefix)/opt/...`. Measured on a clean
#    macOS runner: the closure contains 22 such files (nh3, cryptography,
#    tree-sitter-language-pack, Pillow's `.dylibs`, pypdfium2's `libpdfium.dylib`), they are
#    linked with no header padding, and the first rewrite fails with
#
#      Failed changing dylib ID of .../site-packages/nh3/nh3.abi3.so
#        from @rpath/nh3.abi3.so
#      Updated load commands do not fit in the header
#
#    which makes `brew install` exit 1 even though the keg installed completely. There is no
#    formula-level opt-out: `fix_dynamic_linkage` walks the WHOLE keg (`path.find`) and runs
#    unconditionally for a source build. But `finish()` orders the steps
#    `link` -> `install_service` -> `fix_dynamic_linkage` -> `post_install`, so a venv
#    created in `post_install` simply does not exist when the scan happens. Dylib IDs are
#    meaningless for Python extension modules anyway — they are dlopen'd, never linked
#    against by name — so nothing is lost by keeping them out of that pass.
#
#    Consequence to respect when editing: `bin/personalclaw` must be a real file at `install`
#    time, because `link` also runs before `post_install`. Hence `write_exec_script` rather
#    than `install_symlink`.
class Personalclaw < Formula
  desc "Self-hosted personal AI agent - chat via Slack, dashboard, or CLI"
  homepage "https://personalclaw.dev"
  # A release bump rewrites THIS url and the sha256 below, and nothing else in the file.
  # The opaque `packages/<a>/<b>/<digest>/` path is mandatory — `brew style`'s
  # FormulaAudit/PyPiUrls cop rejects the predictable `packages/source/p/...` form — so the
  # path cannot be derived from the version by hand. Regenerate both lines with:
  #
  #   curl -s https://pypi.org/pypi/personalclaw/<VERSION>/json \
  #     | python3 -c 'import json,sys; u=[u for u in json.load(sys.stdin)["urls"] \
  #         if u["packagetype"]=="sdist"][0]; \
  #         print(f"""  url "{u["url"]}"\n  sha256 "{u["digests"]["sha256"]}"""")'
  #
  # Deliberately NO `head` spec. A git checkout has no built SPA (`static/dist` is a symlink
  # produced by `make web-build`, which needs Node), so `--HEAD` would install a gateway that
  # serves no dashboard. One install path that works beats two where one is a trap.
  url "https://files.pythonhosted.org/packages/76/ba/0c17014b9a1ac815c97d1fd583ae50445426a033247a374353d5b586c465/personalclaw-0.1.3.tar.gz"
  sha256 "40322c39eceb849908dbf190c7932b58c570dc4a600dba0641697ba210e37f20"
  license "MIT"

  livecheck do
    url :stable
    strategy :pypi
  end

  # Upstream pins `requires-python = ">=3.12,<3.14"`. The upper bound is deliberate, not
  # stale: on 3.14 the connector-pack parse fence refuses every import inside a pack
  # script. 3.13 is the newest interpreter upstream CI verifies, so it is what we build on.
  depends_on "python@3.13"

  # DECLARED, not inherited. Homebrew's default is network-allowed in every phase, but
  # `HOMEBREW_FORMULA_POSTINSTALL_NETWORK=deny` flips it — and for this formula that is not a
  # hardening knob, it is a total install failure, because resolving the dependency closure
  # IS the post-install step. Saying so here makes the requirement visible instead of
  # something a user discovers from a broken keg.
  allow_network_access! :postinstall

  def install
    # Stage the verified sdist for post_install to build from, so the thing that gets
    # installed is still the artifact this formula's sha256 covers — not a second download.
    (libexec/"sdist").install Dir["*"]
    bin.write_exec_script libexec/"venv/bin/personalclaw"
  end

  # `post_install_steps` is a DECLARATIVE step list (`mkdir_p`, `chmod`, …) and cannot express
  # "create a virtualenv and resolve a dependency closure into it", so the cop's suggestion
  # does not apply. `def post_install` is still the honoured hook — Homebrew 7.0.6 runs it at
  # formula_installer.rb: `post_install if post_install_steps_defined? || post_install_defined?`.
  def post_install
    # A dedicated venv, never Homebrew's shared site-packages: PersonalClaw installs an app
    # bundle's own Python dependencies into its interpreter at runtime
    # (apps/app_manager.py::_install_python_deps), so it needs an environment it may write to
    # rather than an externally-managed one.
    #
    # An absolute interpreter path, not a bare `python3.13`: `post_install` does NOT run
    # under Homebrew's superenv, so a declared dependency's bin is not on PATH here.
    rm_r(libexec/"venv") if (libexec/"venv").exist?
    system formula_opt_bin("python@3.13")/"python3.13", "-m", "venv", libexec/"venv"

    # --prefer-binary: take a published wheel when one exists for this platform and fall back
    # to an sdist only when it does not. Without it pip builds numpy and lxml from source and
    # the install takes an order of magnitude longer.
    system libexec/"venv/bin/python", "-m", "pip", "install",
           "--no-cache-dir", "--prefer-binary", libexec/"sdist"
  end

  def caveats
    <<~EOS
      Next step — create the config home and pick a provider:
        personalclaw setup

      Then start the dashboard on http://localhost:10000:
        personalclaw gateway

      State lives in ~/.personalclaw. Pre-1.0 releases may change its shape without an
      automatic migration, so take a snapshot before upgrading:
        personalclaw snapshot

      This formula resolves PersonalClaw's Python dependencies from PyPI during
      `brew install`, so the install needs network and is not bit-for-bit reproducible.
      See the comment at the top of the formula for why.
    EOS
  end

  test do
    assert_match "personalclaw #{version}", shell_output("#{bin}/personalclaw --version")

    # The CLI must be usable against a throwaway home, never the invoking user's.
    ENV["PERSONALCLAW_HOME"] = testpath/"home"
    assert_match "doctor", shell_output("#{bin}/personalclaw --help")
  end
end
